package com.waqiti.currency.model;

/**
 * Alert Types for Treasury Operations
 */
public enum AlertType {
    CURRENCY_CONVERSION_PERMANENT_FAILURE,
    HIGH_VALUE_CONVERSION_FAILURE,
    EXCHANGE_RATE_UNAVAILABLE,
    EXCHANGE_RATE_SYSTEM_FAILURE,
    UNSUPPORTED_CURRENCY_PAIR_DEMAND,
    CONVERSION_VOLUME_ANOMALY,
    REFUND_PROCESSING_FAILURE
}
