package com.waqiti.kyc.config;

import com.waqiti.common.security.keycloak.BaseKeycloakSecurityConfig;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;
import lombok.extern.slf4j.Slf4j;

/**
 * Keycloak security configuration for KycService
 * Auto-generated by migration script
 */
@Slf4j
@Configuration
@ConditionalOnProperty(name = "keycloak.enabled", havingValue = "true")
@Order(1)
public class KycServiceKeycloakConfig extends BaseKeycloakSecurityConfig {

    @Bean
    @Primary
    public SecurityFilterChain kycserviceKeycloakFilterChain(HttpSecurity http) throws Exception {
        return createKeycloakSecurityFilterChain(http, "kyc-service", httpSecurity -> {
            httpSecurity.authorizeHttpRequests(authz -> authz
                // Public endpoints
                .requestMatchers("/actuator/health", "/actuator/info").permitAll()
                .requestMatchers("/swagger-ui/**", "/v3/api-docs/**").permitAll()
                
                // KYC service endpoints with role-based access
                .requestMatchers("/api/v1/kyc/verify/**").hasAnyRole("USER", "ADMIN", "SERVICE")
                .requestMatchers("/api/v1/kyc/international/**").hasAnyRole("USER", "ADMIN", "SERVICE")
                .requestMatchers("/api/v1/kyc/documents/**").hasAnyRole("USER", "ADMIN", "SERVICE")
                .requestMatchers("/api/v1/kyc/status/**").hasAnyRole("USER", "ADMIN", "SERVICE")
                .requestMatchers("/api/v1/**").authenticated()
                
                // Admin endpoints
                .requestMatchers("/admin/**").hasRole("ADMIN")
                
                // Internal service-to-service endpoints
                .requestMatchers("/internal/**").hasRole("SERVICE")
                
                // All other endpoints require authentication
                .anyRequest().authenticated()
            );
        });
    }
}
