package com.waqiti.security.domain;

public enum SecurityAction {
    NO_ACTION,
    LOG_ONLY,
    ALERT_SENT,
    ACCOUNT_LOCKED,
    TRANSACTION_BLOCKED,
    APPLICATION_BLOCKED,
    ADDITIONAL_VERIFICATION_REQUIRED,
    MANUAL_REVIEW_REQUIRED,
    ACCOUNT_SUSPENDED,
    LAW_ENFORCEMENT_NOTIFIED
}