package com.waqiti.security.domain;

public enum SecurityEventType {
    // Authentication Events
    FAILED_LOGIN_ATTEMPT,
    SUCCESSFUL_LOGIN,
    ACCOUNT_LOCKED,
    PASSWORD_RESET_REQUEST,
    MFA_SETUP,
    MFA_VERIFICATION_FAILED,
    
    // Transaction Events
    SUSPICIOUS_TRANSACTION,
    HIGH_VALUE_TRANSACTION,
    UNUSUAL_TRANSACTION_PATTERN,
    MULTIPLE_FAILED_TRANSACTIONS,
    VELOCITY_RULE_VIOLATION,
    
    // Fraud Detection
    DEVICE_FINGERPRINT_MISMATCH,
    GEOLOCATION_ANOMALY,
    BEHAVIORAL_ANOMALY,
    BLACKLIST_HIT,
    
    // System Security
    UNAUTHORIZED_API_ACCESS,
    RATE_LIMIT_EXCEEDED,
    SUSPICIOUS_USER_AGENT,
    SQL_INJECTION_ATTEMPT,
    XSS_ATTEMPT,
    
    // BNPL-Specific Events
    SUSPICIOUS_BNPL_APPLICATION,
    BNPL_VELOCITY_VIOLATION,
    BNPL_CREDIT_MISMATCH,
    BNPL_HIGH_RISK_MERCHANT,
    BNPL_APPLICATION_PATTERN_ANOMALY,
    
    // Compliance
    AML_RULE_TRIGGERED,
    KYC_VERIFICATION_FAILED,
    SANCTIONS_SCREENING_HIT,
    REGULATORY_REPORTING_REQUIRED
}