package com.waqiti.compliance.contracts.dto;

/**
 * Categories of compliance findings
 */
public enum FindingCategory {
    AUTHENTICATION,
    AUTHORIZATION,
    ENCRYPTION,
    DATA_PROTECTION,
    ACCESS_CONTROL,
    NETWORK_SECURITY,
    VULNERABILITY,
    MISCONFIGURATION,
    POLICY_VIOLATION,
    AUDIT_LOGGING,
    INCIDENT_RESPONSE,
    BUSINESS_CONTINUITY,
    PRIVACY,
    COMPLIANCE_GAP,
    SECURITY_WEAKNESS,
    CODE_QUALITY,
    INFRASTRUCTURE,
    APPLICATION,
    DATABASE,
    API_SECURITY,
    CLOUD_SECURITY,
    CONTAINER_SECURITY,
    SUPPLY_CHAIN,
    THIRD_PARTY_RISK,
    OPERATIONAL,
    ORGANIZATIONAL,
    OTHER
}
