package com.waqiti.common.compliance.dto;

import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import com.fasterxml.jackson.annotation.JsonFormat;

import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;

/**
 * Comprehensive DTOs for regulatory compliance reporting system
 */
public class ComplianceDTOs {

    // Core Compliance Report DTOs
    
    @Data
    @Builder(toBuilder = true)
    public static class ComplianceReport {
        @NotBlank(message = "Report ID is required")
        private String reportId;

        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;

        private String title;

        @NotNull(message = "Report period is required")
        private ComplianceReportPeriod reportPeriod;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime reportPeriodStart;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime reportPeriodEnd;

        private String regulatoryAuthority;

        @NotBlank(message = "Generated by is required")
        private String generatedBy;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime generatedAt;
        
        @NotNull(message = "Status is required")
        private ComplianceReportStatus status;
        
        private String storagePath;
        private long fileSize;
        private String checksum;
        private boolean encrypted;
        private ComplianceValidationResult validationResult;
        @Builder.Default
        private Map<String, Object> metadata = new HashMap<>();
        private String error;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime submittedAt;
        private String submissionConfirmation;
    }
    
    @Data
    @Builder
    public static class ComplianceReportRequest {
        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;
        
        @NotNull(message = "Report period is required")
        private ComplianceReportPeriod reportPeriod;
        
        @NotBlank(message = "Generated by is required")
        private String generatedBy;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate startDate;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate endDate;
        
        @Builder.Default
        private Map<String, String> parameters = new HashMap<>();
        
        @NotNull(message = "Priority is required")
        @Builder.Default
        private ComplianceReportPriority priority = ComplianceReportPriority.NORMAL;
        
        @Builder.Default
        private List<String> recipients = new ArrayList<>();
        @Builder.Default
        private boolean autoSubmit = false;
        private String regulatoryAuthority;
    }
    
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ComplianceReportData {
        @NotBlank(message = "Report content is required")
        private String reportContent;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime generatedAt;

        @Builder.Default
        private Map<String, Object> metadata = new HashMap<>();
        @Builder.Default
        private List<ComplianceDataPoint> dataPoints = new ArrayList<>();
        @Builder.Default
        private List<ComplianceMetric> metrics = new ArrayList<>();
        private ComplianceRiskAssessment riskAssessment;

        // Transaction-specific fields for CTR/SAR reports
        private String transactionId;
        private String transactionLocation;
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime transactionDate;
        private String transactionType;
        private BigDecimal amount;
        private String accountNumber;

        // Customer-specific fields
        private String customerId;
        private String customerName;
        private String customerAddress;
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate customerDateOfBirth;
        private String customerSSN;
        private String customerPhone;
        private String customerOccupation;

        // Beneficiary fields (for CTR)
        private String beneficiaryName;
        private String beneficiaryAddress;
        private String beneficiaryRelationship;

        // SAR-specific fields
        private String routingNumber;
        private String suspiciousActivityDescription;
        @Builder.Default
        private List<String> riskFactors = new ArrayList<>();
        private BigDecimal mlScore;
        private String patternAnalysis;

        // Law enforcement fields (for SAR)
        private boolean lawEnforcementContacted;
        private String lawEnforcementAgency;
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate lawEnforcementContactDate;
        private String lawEnforcementBadgeNumber;
    }
    
    @Data
    @Builder(toBuilder = true)
    public static class ComplianceReportDocument {
        @NotBlank(message = "Report ID is required")
        private String reportId;

        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;

        private String title;

        @NotBlank(message = "Content is required")
        private String content;

        private String contentType;
        private String format;
        private int fileSize;
        private boolean encrypted;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime generatedAt;

        private String generatedBy;

        private java.util.Map<String, Object> metadata;

        /**
         * Confidentiality level for the report (e.g., "HIGH", "CONFIDENTIAL", "RESTRICTED")
         * Critical for SARs and other sensitive regulatory filings
         */
        private String confidentialityLevel;

        /**
         * Retention period in days - regulatory requirement for document retention
         * E.g., SAR/CTR require 7 years (2555 days)
         */
        private Integer retentionPeriod;
    }
    
    // Validation DTOs
    
    @Data
    @Builder
    public static class ComplianceValidationResult {
        private boolean valid;
        @Builder.Default
        private List<String> errors = new ArrayList<>();
        @Builder.Default
        private List<String> warnings = new ArrayList<>();
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime validatedAt;
        
        private String validatedBy;
        @Builder.Default
        private Map<String, Object> validationDetails = new HashMap<>();
    }
    
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ComplianceReportValidationRequest {
        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;
        
        @NotNull(message = "Report data is required")
        private ComplianceReportData reportData;
        
        @NotBlank(message = "Validated by is required")
        private String validatedBy;
    }
    
    // Submission DTOs
    
    @Data
    @Builder
    public static class ComplianceSubmissionRequest {
        @NotBlank(message = "Regulatory authority is required")
        private String regulatoryAuthority;
        
        @NotBlank(message = "Submitted by is required")
        private String submittedBy;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime submissionDeadline;
        
        @Builder.Default
        private Map<String, String> submissionParameters = new HashMap<>();
        @Builder.Default
        private List<String> attachments = new ArrayList<>();
        @Builder.Default
        private boolean urgentSubmission = false;
        private String submissionNotes;
    }
    
    @Data
    @Builder
    public static class ComplianceSubmissionResult {
        private String submissionId;

        @NotBlank(message = "Report ID is required")
        private String reportId;

        private boolean successful;
        private boolean success;  // Alias for successful
        private String confirmationNumber;
        private String errorMessage;
        private String statusMessage;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime submittedAt;

        private String regulatoryAuthority;
        @Builder.Default
        private Map<String, Object> submissionDetails = new HashMap<>();
    }
    
    // SAR (Suspicious Activity Report) DTOs
    
    @Data
    @Builder
    public static class SARRequest {
        @NotBlank(message = "Transaction ID is required")
        private String transactionId;
        
        @NotBlank(message = "Generated by is required")
        private String generatedBy;
        
        @NotBlank(message = "Suspicious activity description is required")
        private String suspiciousActivity;
        
        @NotNull(message = "Risk score is required")
        @DecimalMin(value = "0.0", message = "Risk score cannot be negative")
        @DecimalMax(value = "1.0", message = "Risk score cannot exceed 1.0")
        private BigDecimal riskScore;
        
        @NotBlank(message = "Customer ID is required")
        private String customerId;
        
        @NotNull(message = "Transaction amount is required")
        private BigDecimal transactionAmount;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime transactionDate;
        
        private String additionalDetails;
        @Builder.Default
        private List<String> supportingDocuments = new ArrayList<>();
        @Builder.Default
        private SARPriority priority = SARPriority.NORMAL;
    }
    
    // CTR (Currency Transaction Report) DTOs
    
    @Data
    @Builder
    public static class CTRRequest {
        @NotBlank(message = "Transaction ID is required")
        private String transactionId;
        
        @NotBlank(message = "Generated by is required")
        private String generatedBy;
        
        @NotBlank(message = "Customer ID is required")
        private String customerId;
        
        @NotNull(message = "Transaction amount is required")
        @DecimalMin(value = "10000.00", message = "CTR threshold is $10,000")
        private BigDecimal transactionAmount;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime transactionDate;
        
        private String transactionType;
        private String customerName;
        private String customerAddress;
        private String customerSSN;
        private String customerDateOfBirth;
        @Builder.Default
        private List<String> supportingDocuments = new ArrayList<>();
    }
    
    // Statistics and Summary DTOs
    
    @Data
    @Builder
    public static class ComplianceReportSummary {
        private List<ComplianceReport> reports;
        private long totalReports;
        private long completedReports;
        private long pendingReports;
        private long failedReports;
        private long inProgressReports;
        private long submittedReports;

        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime lastUpdated;

        @Builder.Default
        private Map<ComplianceReportType, Long> reportsByType = new HashMap<>();
        @Builder.Default
        private Map<ComplianceReportStatus, Long> reportsByStatus = new HashMap<>();
    }
    
    @Data
    @Builder
    public static class ComplianceDashboardStatistics {
        private long totalReportsGenerated;
        private long pendingReports;
        private long submittedReports;
        private long failedReports;
        private long sarReports;
        private long ctrReports;
        private double averageGenerationTimeMinutes;
        private double complianceScore;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime lastUpdated;
        
        @Builder.Default
        private List<ComplianceAlert> activeAlerts = new ArrayList<>();
        @Builder.Default
        private List<ComplianceTrend> trends = new ArrayList<>();
    }
    
    @Data
    @Builder
    public static class ComplianceDataPoint {
        @NotBlank(message = "Data point name is required")
        private String name;
        
        @NotNull(message = "Value is required")
        private Object value;
        
        private String category;
        private String description;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime timestamp;
    }
    
    @Data
    @Builder
    public static class ComplianceMetric {
        @NotBlank(message = "Metric name is required")
        private String name;
        
        @NotNull(message = "Metric value is required")
        private BigDecimal value;
        
        private String unit;
        private String category;
        private ComplianceMetricType type;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime measurementTime;
    }
    
    // Filter and Search DTOs
    
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ComplianceReportFilter {
        private ComplianceReportType reportType;
        private ComplianceReportStatus status;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate startDate;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate endDate;
        
        private String generatedBy;
        private ComplianceReportPriority priority;
        
        @Min(value = 1, message = "Page must be at least 1")
        @Builder.Default
        private int page = 1;
        
        @Min(value = 1, message = "Size must be at least 1")
        @Max(value = 100, message = "Size cannot exceed 100")
        @Builder.Default
        private int size = 20;
        
        @Builder.Default
        private String sortBy = "generatedAt";
        @Builder.Default
        private String sortDirection = "DESC";
    }
    
    // Risk Assessment DTOs
    
    @Data
    @Builder
    public static class ComplianceRiskAssessment {
        @NotNull(message = "Overall risk level is required")
        private ComplianceRiskLevel overallRiskLevel;
        
        @NotNull(message = "Risk score is required")
        @DecimalMin(value = "0.0", message = "Risk score cannot be negative")
        @DecimalMax(value = "1.0", message = "Risk score cannot exceed 1.0")
        private BigDecimal riskScore;
        
        @Builder.Default
        private List<RiskFactor> riskFactors = new ArrayList<>();
        @Builder.Default
        private List<MitigationAction> mitigationActions = new ArrayList<>();
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime assessmentDate;
        
        private String assessedBy;
        private String assessmentNotes;
    }
    
    @Data
    @Builder
    public static class RiskFactor {
        @NotBlank(message = "Factor name is required")
        private String factorName;
        
        @NotNull(message = "Impact level is required")
        private RiskImpactLevel impactLevel;
        
        @NotNull(message = "Likelihood is required")
        private RiskLikelihood likelihood;
        
        private String description;
        private BigDecimal weightage;
    }
    
    @Data
    @Builder
    public static class MitigationAction {
        @NotBlank(message = "Action description is required")
        private String actionDescription;
        
        @NotNull(message = "Priority is required")
        private MitigationPriority priority;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate dueDate;
        
        private String assignedTo;
        private MitigationStatus status;
    }
    
    // Calendar and Deadline DTOs
    
    @Data
    @Builder
    public static class RegulatoryDeadlineCalendar {
        @Builder.Default
        private List<RegulatoryDeadline> upcomingDeadlines = new ArrayList<>();
        private long totalDeadlines;
        private long criticalDeadlines;
        private long overdueTasks;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime lastUpdated;
    }
    
    @Data
    @Builder
    public static class RegulatoryDeadline {
        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;
        
        @JsonFormat(pattern = "yyyy-MM-dd")
        @NotNull(message = "Due date is required")
        private LocalDate dueDate;
        
        @NotBlank(message = "Authority is required")
        private String authority;
        
        @NotNull(message = "Priority is required")
        private ComplianceReportPriority priority;
        
        private String description;
        private DeadlineStatus status;
        private int daysRemaining;
    }
    
    // Audit Trail DTOs
    
    @Data
    @Builder
    public static class ComplianceAuditTrail {
        private long totalActivities;
        private long reportGenerations;
        private long reportSubmissions;
        private long validationActivities;
        @Builder.Default
        private List<ComplianceAuditActivity> activities = new ArrayList<>();
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime fromDate;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime toDate;
    }
    
    @Data
    @Builder
    public static class ComplianceAuditActivity {
        @NotBlank(message = "Activity ID is required")
        private String activityId;
        
        @NotNull(message = "Activity type is required")
        private ComplianceActivityType activityType;
        
        @NotBlank(message = "User ID is required")
        private String userId;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime timestamp;
        
        private String description;
        private String reportId;
        @Builder.Default
        private Map<String, Object> details = new HashMap<>();
        private String ipAddress;
        private String userAgent;
    }
    
    // System Health DTOs
    
    @Data
    @Builder
    public static class ComplianceSystemHealth {
        @NotNull(message = "Overall status is required")
        private SystemHealthStatus overallStatus;
        
        private SystemHealthStatus reportGenerationStatus;
        private SystemHealthStatus submissionServiceStatus;
        private SystemHealthStatus auditServiceStatus;
        private SystemHealthStatus storageServiceStatus;
        private SystemHealthStatus encryptionServiceStatus;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime lastHealthCheck;
        
        @Builder.Default
        private List<HealthCheckResult> healthChecks = new ArrayList<>();
        private String overallMessage;
    }
    
    @Data
    @Builder
    public static class HealthCheckResult {
        @NotBlank(message = "Component name is required")
        private String componentName;
        
        @NotNull(message = "Status is required")
        private SystemHealthStatus status;
        
        private String message;
        private long responseTimeMs;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime checkedAt;
    }
    
    // Scheduling DTOs
    
    @Data
    @Builder
    public static class ComplianceReportScheduleRequest {
        @NotNull(message = "Report type is required")
        private ComplianceReportType reportType;
        
        @NotBlank(message = "Cron expression is required")
        @Pattern(regexp = "^[0-9*\\-,/]+ [0-9*\\-,/]+ [0-9*\\-,/]+ [0-9*\\-,/]+ [0-9*\\-,/]+ [0-9*\\-,/?]+$",
                message = "Invalid cron expression")
        private String cronExpression;
        
        @NotBlank(message = "Scheduled by is required")
        private String scheduledBy;
        
        @Builder.Default
        private Map<String, String> parameters = new HashMap<>();
        @Builder.Default
        private List<String> recipients = new ArrayList<>();
        @Builder.Default
        private boolean autoSubmit = false;
        private String description;
    }
    
    // Alert and Notification DTOs
    
    @Data
    @Builder
    public static class ComplianceAlert {
        @NotBlank(message = "Alert ID is required")
        private String alertId;
        
        @NotNull(message = "Alert level is required")
        private ComplianceAlertLevel level;
        
        @NotBlank(message = "Title is required")
        private String title;
        
        @NotBlank(message = "Message is required")
        private String message;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime createdAt;
        
        private String reportId;
        private ComplianceReportType reportType;
        @Builder.Default
        private boolean acknowledged = false;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime acknowledgedAt;
        
        private String acknowledgedBy;
    }
    
    @Data
    @Builder
    public static class ComplianceTrend {
        @NotBlank(message = "Trend name is required")
        private String trendName;
        
        @NotNull(message = "Trend direction is required")
        private TrendDirection direction;
        
        @NotNull(message = "Current value is required")
        private BigDecimal currentValue;
        
        @NotNull(message = "Previous value is required")
        private BigDecimal previousValue;
        
        @NotNull(message = "Percentage change is required")
        private BigDecimal percentageChange;
        
        private String category;
        
        @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
        private LocalDateTime calculatedAt;
    }

    // Enums

    public static enum ComplianceReportType {
    // Financial Compliance
    SAR_FILING,
    CTR_FILING,
    AML_BSA_MONTHLY,
    AML_COMPLIANCE,
    KYC_COMPLIANCE,
    BSA_AML_REPORT,

    // Security Compliance
    PCI_DSS_COMPLIANCE,
    SOC2_TYPE_II,
    HIPAA_COMPLIANCE,

    // Regulatory Compliance
    SOX_COMPLIANCE,
    GDPR_COMPLIANCE,
    FFIEC_COMPLIANCE,

    // Screening & Monitoring
    SANCTIONS_SCREENING,
    TRANSACTION_MONITORING,
    CUSTOMER_DUE_DILIGENCE,
    PEP_SCREENING,
    ADVERSE_MEDIA_SCREENING,

    // Operational Reports
    DAILY_TRANSACTION_SUMMARY,
    AML_SCREENING_SUMMARY,
    FRAUD_DETECTION_SUMMARY,
    AUDIT_LOG_SUMMARY,
    RISK_ASSESSMENT,
    REGULATORY_FILING,
    AUDIT_REPORT,
    POLICY_REVIEW,
    TRAINING_COMPLIANCE,
    INCIDENT_REPORT,

    // Custom Reports
    CUSTOM_COMPLIANCE_REPORT
}

    public static enum ComplianceReportStatus {
    PENDING,
    IN_PROGRESS,
    COMPLETED,
    FAILED,
    SUBMITTED,
    ARCHIVED,
    NOT_FOUND
}

    public static enum ComplianceReportPeriod {
    DAILY,
    WEEKLY,
    MONTHLY,
    QUARTERLY,
    ANNUALLY,
    ON_DEMAND
}

    public static enum ComplianceReportPriority {
    LOW,
    NORMAL,
    HIGH,
    CRITICAL,
    URGENT
}

    public static enum SARPriority {
    NORMAL,
    HIGH,
    URGENT
}

    public static enum ComplianceRiskLevel {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}

    public static enum RiskImpactLevel {
    MINIMAL,
    MINOR,
    MODERATE,
    MAJOR,
    SEVERE
}

    public static enum RiskLikelihood {
    RARE,
    UNLIKELY,
    POSSIBLE,
    LIKELY,
    CERTAIN
}

    public static enum MitigationPriority {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}

    public static enum MitigationStatus {
    NOT_STARTED,
    IN_PROGRESS,
    COMPLETED,
    DEFERRED,
    CANCELLED
}

    public static enum DeadlineStatus {
    UPCOMING,
    DUE_TODAY,
    OVERDUE,
    COMPLETED
}

    public static enum ComplianceActivityType {
    REPORT_GENERATED,
    REPORT_SUBMITTED,
    REPORT_VALIDATED,
    REPORT_FAILED,
    SCHEDULE_CREATED,
    SCHEDULE_CANCELLED,
    ALERT_GENERATED,
    ALERT_ACKNOWLEDGED
}

    public static enum SystemHealthStatus {
    HEALTHY,
    DEGRADED,
    UNHEALTHY,
    UNKNOWN
}

    public static enum ComplianceAlertLevel {
    INFO,
    WARNING,
    ERROR,
    CRITICAL
}

    public static enum TrendDirection {
    UP,
    DOWN,
    STABLE
}

    public static enum ComplianceMetricType {
    COUNT,
    PERCENTAGE,
    AMOUNT,
    DURATION,
    RATIO
}

    public static enum ReportFormat {
    PDF,
    XML,
    JSON,
    CSV,
    EXCEL,
    TEXT
}
} // End of ComplianceDTOs class
