package com.waqiti.transaction.domain;

public enum BlockReason {
    FRAUD_SUSPECTED,
    COMPLIANCE_REVIEW,
    MANUAL_REVIEW,
    SYSTEM_MAINTENANCE,
    REGULATORY_HOLD,
    AML_SCREENING,
    TEMPORARY_HOLD,
    PERMANENT_BAN,
    ACCOUNT_CLOSED,
    SUSPICIOUS_ACTIVITY,
    LARGE_AMOUNT_REVIEW,
    VELOCITY_CHECK,
    SANCTIONS_CHECK,
    TECHNICAL_ISSUE,
    RISK_ASSESSMENT
}