-- Add optimistic locking version column to all entities for concurrent update protection
-- This migration adds @Version support for JPA optimistic locking

-- User Service
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS user_profiles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS verification_tokens ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS mfa_configurations ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS mfa_verification_codes ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS family_guardianships ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS guardian_approval_requests ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Wallet Service
ALTER TABLE IF EXISTS wallets ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS wallet_holds ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS fund_reservations ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Payment Service
ALTER TABLE IF EXISTS payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS payment_requests ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS payment_methods ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS payment_links ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS payment_link_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS split_payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS split_payment_participants ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS scheduled_payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS scheduled_payment_executions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS qr_code_payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS instant_deposits ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS ach_transfers ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS check_deposits ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS nfc_sessions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS nfc_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS offline_payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS paypal_customers ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS paypal_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS webhook_delivery_attempts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS business_profiles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Ledger Service
ALTER TABLE IF EXISTS ledger_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS ledger_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS journal_entries ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS audit_trails ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Crypto Service
ALTER TABLE IF EXISTS crypto_wallets ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS crypto_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS crypto_addresses ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS crypto_price_history ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS sanctioned_addresses ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS high_risk_addresses ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS crypto_fraud_events ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Rewards Service
ALTER TABLE IF EXISTS rewards_tiers ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS user_rewards_account ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS rewards_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS redemption_requests ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- ATM Service
ALTER TABLE IF EXISTS atm_cards ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS atm_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS cardless_withdrawals ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Family Account Service
ALTER TABLE IF EXISTS family_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS family_members ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS family_spending_rules ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Investment Service
ALTER TABLE IF EXISTS investment_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS investment_portfolios ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS investment_holdings ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS investment_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS market_orders ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Card Service
ALTER TABLE IF EXISTS cards ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS card_transactions ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS virtual_cards ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS card_limits ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Expense Service
ALTER TABLE IF EXISTS expenses ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS expense_categories ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS budgets ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS budget_alerts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Merchant Service
ALTER TABLE IF EXISTS merchants ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS merchant_accounts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS merchant_settlements ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS merchant_disputes ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Loan Service
ALTER TABLE IF EXISTS loans ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS loan_applications ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS loan_payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS loan_schedules ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- KYC Service
ALTER TABLE IF EXISTS kyc_profiles ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS kyc_documents ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS kyc_verifications ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS kyc_risk_assessments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Compliance Service
ALTER TABLE IF EXISTS compliance_checks ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS sanctions_screenings ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS aml_alerts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS suspicious_activity_reports ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Notification Service
ALTER TABLE IF EXISTS notifications ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS notification_templates ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS notification_preferences ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Fraud Service
ALTER TABLE IF EXISTS fraud_alerts ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS fraud_rules ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS fraud_investigations ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE IF EXISTS blacklisted_entities ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

-- Create indexes on version columns for frequently updated tables
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_version ON users(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_wallets_version ON wallets(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_version ON transactions(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_payments_version ON payments(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_crypto_transactions_version ON crypto_transactions(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cards_version ON cards(version) WHERE version > 0;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loans_version ON loans(version) WHERE version > 0;

-- Add comment explaining the purpose
COMMENT ON COLUMN users.version IS 'Optimistic locking version for concurrent update protection';
COMMENT ON COLUMN wallets.version IS 'Optimistic locking version for concurrent update protection';
COMMENT ON COLUMN transactions.version IS 'Optimistic locking version for concurrent update protection';
COMMENT ON COLUMN payments.version IS 'Optimistic locking version for concurrent update protection';