package com.waqiti.common.compliance;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Filter criteria for searching and filtering compliance reports
 * 
 * Supports complex filtering scenarios for compliance dashboards,
 * reporting systems, and regulatory inquiries.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ComplianceReportFilter {

    /**
     * Report type filter
     */
    private List<ComplianceReportType> reportTypes;

    /**
     * Status filter
     */
    private List<ComplianceReportStatus> statuses;

    /**
     * Priority filter
     */
    private List<ComplianceReport.ReportPriority> priorities;

    /**
     * Created date range
     */
    private LocalDateTime createdAfter;
    private LocalDateTime createdBefore;

    /**
     * Modified date range
     */
    private LocalDateTime modifiedAfter;
    private LocalDateTime modifiedBefore;

    /**
     * Filing deadline range
     */
    private LocalDateTime deadlineAfter;
    private LocalDateTime deadlineBefore;

    /**
     * Report period range
     */
    private LocalDateTime reportPeriodStart;
    private LocalDateTime reportPeriodEnd;

    /**
     * Created by user filter
     */
    private List<String> createdByUsers;

    /**
     * Modified by user filter
     */
    private List<String> modifiedByUsers;

    /**
     * Approved by user filter
     */
    private List<String> approvedByUsers;

    /**
     * Regulatory authority filter
     */
    private List<String> regulatoryAuthorities;

    /**
     * Jurisdiction filter
     */
    private List<String> jurisdictionCodes;

    /**
     * Title/description text search
     */
    private String searchText;

    /**
     * Tags filter
     */
    private List<String> tags;

    /**
     * Quality score range
     */
    private Integer minimumQualityScore;
    private Integer maximumQualityScore;

    /**
     * Risk level filter
     */
    private List<String> riskLevels;

    /**
     * Transaction count range
     */
    private Integer minimumTransactionCount;
    private Integer maximumTransactionCount;

    /**
     * Customer count range
     */
    private Integer minimumCustomerCount;
    private Integer maximumCustomerCount;

    /**
     * Financial amount range
     */
    private Double minimumTotalAmount;
    private Double maximumTotalAmount;

    /**
     * Currency filter
     */
    private List<String> currencies;

    /**
     * Compliance flags filter
     */
    private List<String> complianceFlags;

    /**
     * Supporting document filter
     */
    private DocumentFilter documentFilter;

    /**
     * Custom metadata filters
     */
    private Map<String, Object> metadataFilters;

    /**
     * External reference filters
     */
    private List<String> externalSystems;
    private List<String> externalReferenceTypes;

    /**
     * Report configuration filters
     */
    private Boolean autoGenerated;
    private Boolean requiresLegalReview;
    private Boolean requiresComplianceReview;

    /**
     * Workflow status filters
     */
    private List<String> workflowSteps;
    private List<String> assignedUsers;

    /**
     * Advanced filters
     */
    private AdvancedFilter advancedFilter;

    /**
     * Pagination and sorting
     */
    @Builder.Default
    private int page = 0;
    @Builder.Default
    private int size = 20;
    @Builder.Default
    private String sortBy = "createdAt";
    @Builder.Default
    private SortDirection sortDirection = SortDirection.DESC;

    /**
     * Include related data
     */
    @Builder.Default
    private boolean includeTransactions = false;
    @Builder.Default
    private boolean includeCustomers = false;
    @Builder.Default
    private boolean includeDocuments = false;
    @Builder.Default
    private boolean includeWorkflowHistory = false;
    @Builder.Default
    private boolean includeComments = false;

    /**
     * Document filter criteria
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DocumentFilter {
        private List<String> documentTypes;
        private List<String> fileNames;
        private Long minimumFileSize;
        private Long maximumFileSize;
        private List<String> mimeTypes;
        private LocalDateTime uploadedAfter;
        private LocalDateTime uploadedBefore;
        private List<String> uploadedByUsers;
        private Boolean encrypted;
    }

    /**
     * Advanced filter criteria
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AdvancedFilter {
        private String sqlWhereClause;
        private Map<String, Object> parameters;
        private List<String> includeFields;
        private List<String> excludeFields;
        private String customQuery;
        private Map<String, Object> queryParameters;
    }

    /**
     * Sort direction enumeration
     */
    public enum SortDirection {
        ASC, DESC
    }

    // Utility methods

    /**
     * Check if filter has any criteria set
     */
    public boolean isEmpty() {
        return (reportTypes == null || reportTypes.isEmpty()) &&
               (statuses == null || statuses.isEmpty()) &&
               (priorities == null || priorities.isEmpty()) &&
               createdAfter == null && createdBefore == null &&
               modifiedAfter == null && modifiedBefore == null &&
               deadlineAfter == null && deadlineBefore == null &&
               reportPeriodStart == null && reportPeriodEnd == null &&
               (createdByUsers == null || createdByUsers.isEmpty()) &&
               (modifiedByUsers == null || modifiedByUsers.isEmpty()) &&
               (approvedByUsers == null || approvedByUsers.isEmpty()) &&
               (regulatoryAuthorities == null || regulatoryAuthorities.isEmpty()) &&
               (jurisdictionCodes == null || jurisdictionCodes.isEmpty()) &&
               (searchText == null || searchText.trim().isEmpty()) &&
               (tags == null || tags.isEmpty()) &&
               minimumQualityScore == null && maximumQualityScore == null &&
               (riskLevels == null || riskLevels.isEmpty()) &&
               minimumTransactionCount == null && maximumTransactionCount == null &&
               minimumCustomerCount == null && maximumCustomerCount == null &&
               minimumTotalAmount == null && maximumTotalAmount == null &&
               (currencies == null || currencies.isEmpty()) &&
               (complianceFlags == null || complianceFlags.isEmpty()) &&
               documentFilter == null &&
               (metadataFilters == null || metadataFilters.isEmpty()) &&
               (externalSystems == null || externalSystems.isEmpty()) &&
               (externalReferenceTypes == null || externalReferenceTypes.isEmpty()) &&
               autoGenerated == null &&
               requiresLegalReview == null &&
               requiresComplianceReview == null &&
               (workflowSteps == null || workflowSteps.isEmpty()) &&
               (assignedUsers == null || assignedUsers.isEmpty()) &&
               advancedFilter == null;
    }

    /**
     * Create filter for overdue reports
     */
    public static ComplianceReportFilter createOverdueFilter() {
        return ComplianceReportFilter.builder()
            .deadlineBefore(LocalDateTime.now())
            .statuses(List.of(
                ComplianceReportStatus.DRAFT,
                ComplianceReportStatus.IN_PROGRESS,
                ComplianceReportStatus.PENDING_REVIEW,
                ComplianceReportStatus.UNDER_REVIEW,
                ComplianceReportStatus.REQUIRES_REVISION,
                ComplianceReportStatus.PENDING_APPROVAL,
                ComplianceReportStatus.APPROVED
            ))
            .sortBy("filingDeadline")
            .sortDirection(SortDirection.ASC)
            .build();
    }

    /**
     * Create filter for reports requiring action
     */
    public static ComplianceReportFilter createActionRequiredFilter() {
        return ComplianceReportFilter.builder()
            .statuses(List.of(
                ComplianceReportStatus.REQUIRES_REVISION,
                ComplianceReportStatus.INFO_REQUESTED,
                ComplianceReportStatus.OVERDUE,
                ComplianceReportStatus.FAILED,
                ComplianceReportStatus.ON_HOLD
            ))
            .priorities(List.of(
                ComplianceReport.ReportPriority.CRITICAL,
                ComplianceReport.ReportPriority.HIGH
            ))
            .sortBy("priority")
            .sortDirection(SortDirection.DESC)
            .build();
    }

    /**
     * Create filter for high-priority reports
     */
    public static ComplianceReportFilter createHighPriorityFilter() {
        return ComplianceReportFilter.builder()
            .priorities(List.of(
                ComplianceReport.ReportPriority.CRITICAL,
                ComplianceReport.ReportPriority.HIGH
            ))
            .sortBy("filingDeadline")
            .sortDirection(SortDirection.ASC)
            .build();
    }

    /**
     * Create filter for reports by user
     */
    public static ComplianceReportFilter createUserReportsFilter(String userId) {
        return ComplianceReportFilter.builder()
            .createdByUsers(List.of(userId))
            .sortBy("modifiedAt")
            .sortDirection(SortDirection.DESC)
            .build();
    }

    /**
     * Create filter for regulatory authority
     */
    public static ComplianceReportFilter createRegulatoryAuthorityFilter(String authority) {
        return ComplianceReportFilter.builder()
            .regulatoryAuthorities(List.of(authority))
            .sortBy("filingDeadline")
            .sortDirection(SortDirection.ASC)
            .build();
    }

    /**
     * Create filter for report type
     */
    public static ComplianceReportFilter createReportTypeFilter(ComplianceReportType reportType) {
        return ComplianceReportFilter.builder()
            .reportTypes(List.of(reportType))
            .sortBy("createdAt")
            .sortDirection(SortDirection.DESC)
            .build();
    }

    /**
     * Create filter for date range
     */
    public static ComplianceReportFilter createDateRangeFilter(LocalDateTime from, LocalDateTime to) {
        return ComplianceReportFilter.builder()
            .createdAfter(from)
            .createdBefore(to)
            .sortBy("createdAt")
            .sortDirection(SortDirection.DESC)
            .build();
    }

    /**
     * Create filter for search text
     */
    public static ComplianceReportFilter createSearchFilter(String searchText) {
        return ComplianceReportFilter.builder()
            .searchText(searchText)
            .sortBy("relevance")
            .sortDirection(SortDirection.DESC)
            .build();
    }

    /**
     * Validate filter criteria
     */
    public FilterValidation validate() {
        FilterValidation validation = new FilterValidation();

        // Date range validation
        if (createdAfter != null && createdBefore != null && createdAfter.isAfter(createdBefore)) {
            validation.addError("Created date range invalid: start date must be before end date");
        }

        if (modifiedAfter != null && modifiedBefore != null && modifiedAfter.isAfter(modifiedBefore)) {
            validation.addError("Modified date range invalid: start date must be before end date");
        }

        if (deadlineAfter != null && deadlineBefore != null && deadlineAfter.isAfter(deadlineBefore)) {
            validation.addError("Deadline range invalid: start date must be before end date");
        }

        if (reportPeriodStart != null && reportPeriodEnd != null && reportPeriodStart.isAfter(reportPeriodEnd)) {
            validation.addError("Report period range invalid: start date must be before end date");
        }

        // Numeric range validation
        if (minimumQualityScore != null && maximumQualityScore != null && 
            minimumQualityScore > maximumQualityScore) {
            validation.addError("Quality score range invalid: minimum cannot be greater than maximum");
        }

        if (minimumTransactionCount != null && maximumTransactionCount != null && 
            minimumTransactionCount > maximumTransactionCount) {
            validation.addError("Transaction count range invalid: minimum cannot be greater than maximum");
        }

        if (minimumCustomerCount != null && maximumCustomerCount != null && 
            minimumCustomerCount > maximumCustomerCount) {
            validation.addError("Customer count range invalid: minimum cannot be greater than maximum");
        }

        if (minimumTotalAmount != null && maximumTotalAmount != null && 
            minimumTotalAmount > maximumTotalAmount) {
            validation.addError("Total amount range invalid: minimum cannot be greater than maximum");
        }

        // Pagination validation
        if (page < 0) {
            validation.addError("Page number cannot be negative");
        }

        if (size <= 0 || size > 1000) {
            validation.addError("Page size must be between 1 and 1000");
        }

        // Sort field validation
        if (sortBy == null || sortBy.trim().isEmpty()) {
            validation.addError("Sort field cannot be empty");
        }

        return validation;
    }

    /**
     * Filter validation result
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FilterValidation {
        @Builder.Default
        private List<String> errors = new java.util.ArrayList<>();
        @Builder.Default
        private List<String> warnings = new java.util.ArrayList<>();

        public void addError(String error) {
            errors.add(error);
        }

        public void addWarning(String warning) {
            warnings.add(warning);
        }

        public boolean isValid() {
            return errors.isEmpty();
        }

        public boolean hasWarnings() {
            return !warnings.isEmpty();
        }
    }
}