package com.waqiti.common.compliance;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Summary view of compliance reports for dashboards and listing views
 * 
 * Provides essential information about compliance reports without
 * loading the full report content for performance optimization.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ComplianceReportSummary {

    /**
     * List of reports (for collection summaries)
     */
    private List<ComplianceReport> reports;

    /**
     * Total number of reports
     */
    private long totalReports;

    /**
     * Number of pending reports
     */
    private Long pendingReports;

    /**
     * Number of completed reports
     */
    private Long completedReports;

    /**
     * Number of failed reports
     */
    private Long failedReports;

    /**
     * Number of in-progress reports
     */
    private Long inProgressReports;

    /**
     * Last update timestamp
     */
    private LocalDateTime lastUpdated;

    /**
     * Report identifier
     */
    private String reportId;

    /**
     * Report type
     */
    private ComplianceReportType reportType;

    /**
     * Current status
     */
    private ComplianceReportStatus status;

    /**
     * Report title
     */
    private String title;

    /**
     * Brief description
     */
    private String description;

    /**
     * Priority level
     */
    private ComplianceReport.ReportPriority priority;

    /**
     * Regulatory authority
     */
    private String regulatoryAuthority;

    /**
     * Jurisdiction code
     */
    private String jurisdictionCode;

    /**
     * Filing deadline
     */
    private LocalDateTime filingDeadline;

    /**
     * Report period
     */
    private LocalDateTime reportPeriodStart;
    private LocalDateTime reportPeriodEnd;

    /**
     * Creation information
     */
    private String createdBy;
    private LocalDateTime createdAt;

    /**
     * Last modification information
     */
    private String modifiedBy;
    private LocalDateTime modifiedAt;

    /**
     * Submission information
     */
    private LocalDateTime submittedAt;
    private String submittedBy;

    /**
     * Approval information
     */
    private LocalDateTime approvedAt;
    private String approvedBy;

    /**
     * Filing information
     */
    private LocalDateTime filedAt;
    private String filingConfirmationNumber;

    /**
     * Quality and completion metrics
     */
    private Integer qualityScore;
    private Integer completionPercentage;
    private Integer validationErrorCount;
    private Integer validationWarningCount;

    /**
     * Financial summary
     */
    private FinancialSummary financialSummary;

    /**
     * Data summary
     */
    private DataSummary dataSummary;

    /**
     * Workflow status
     */
    private WorkflowSummary workflowSummary;

    /**
     * Risk assessment
     */
    private RiskSummary riskSummary;

    /**
     * Report tags
     */
    private List<String> tags;

    /**
     * Key metrics
     */
    private Map<String, Object> keyMetrics;

    /**
     * External references count
     */
    private Integer externalReferencesCount;

    /**
     * Supporting documents count
     */
    private Integer documentsCount;

    /**
     * Comments count
     */
    private Integer commentsCount;

    /**
     * Compliance flags count
     */
    private Integer complianceFlagsCount;

    /**
     * Auto-generation information
     */
    private Boolean autoGenerated;
    private LocalDateTime lastAutoUpdate;

    /**
     * Financial summary for the report
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FinancialSummary {
        private BigDecimal totalAmount;
        private String baseCurrency;
        private Integer transactionCount;
        private BigDecimal averageAmount;
        private BigDecimal maximumAmount;
        private BigDecimal minimumAmount;
        private Map<String, BigDecimal> currencyBreakdown;
    }

    /**
     * Data summary for the report
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DataSummary {
        private Integer customerCount;
        private Integer accountCount;
        private Integer merchantCount;
        private Integer transactionCount;
        private LocalDateTime dataFreshnessTimestamp;
        private Double completenessScore;
        private Double accuracyScore;
        private Integer dataSourcesCount;
    }

    /**
     * Workflow summary
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class WorkflowSummary {
        private String currentStep;
        private String assignedTo;
        private LocalDateTime stepStartedAt;
        private Integer totalSteps;
        private Integer completedSteps;
        private List<String> pendingApprovers;
        private Boolean requiresEscalation;
        private LocalDateTime escalationDue;
    }

    /**
     * Risk assessment summary
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RiskSummary {
        private String overallRiskLevel;
        private BigDecimal riskScore;
        private Integer highRiskTransactions;
        private Integer suspiciousActivities;
        private List<String> keyRiskFactors;
        private Boolean requiresEscalation;
    }

    // Utility methods

    /**
     * Check if report is overdue
     */
    public boolean isOverdue() {
        return filingDeadline != null && 
               LocalDateTime.now().isAfter(filingDeadline) && 
               !isSubmitted();
    }

    /**
     * Check if report is submitted
     */
    public boolean isSubmitted() {
        return status == ComplianceReportStatus.SUBMITTED ||
               status == ComplianceReportStatus.FILED ||
               status == ComplianceReportStatus.APPROVED;
    }

    /**
     * Check if report is in draft status
     */
    public boolean isDraft() {
        return status == ComplianceReportStatus.DRAFT ||
               status == ComplianceReportStatus.IN_PROGRESS;
    }

    /**
     * Get days until filing deadline
     */
    public long getDaysUntilDeadline() {
        if (filingDeadline == null) return -1;
        return java.time.Duration.between(LocalDateTime.now(), filingDeadline).toDays();
    }

    /**
     * Check if report requires urgent attention
     */
    public boolean requiresUrgentAttention() {
        return priority == ComplianceReport.ReportPriority.CRITICAL ||
               isOverdue() ||
               (getDaysUntilDeadline() <= 1 && !isSubmitted()) ||
               (workflowSummary != null && Boolean.TRUE.equals(workflowSummary.getRequiresEscalation()));
    }

    /**
     * Get status display class for UI
     */
    public String getStatusDisplayClass() {
        if (status == null) return "status-unknown";
        return status.getCssClass();
    }

    /**
     * Get priority display class for UI
     */
    public String getPriorityDisplayClass() {
        if (priority == null) return "priority-unknown";
        
        return switch (priority) {
            case CRITICAL -> "priority-critical";
            case HIGH -> "priority-high";
            case MEDIUM -> "priority-medium";
            case LOW -> "priority-low";
            case ROUTINE -> "priority-routine";
        };
    }

    /**
     * Get completion status text
     */
    public String getCompletionStatusText() {
        if (completionPercentage == null) return "Unknown";
        
        if (completionPercentage == 0) return "Not Started";
        if (completionPercentage < 25) return "Started";
        if (completionPercentage < 50) return "In Progress";
        if (completionPercentage < 75) return "Mostly Complete";
        if (completionPercentage < 100) return "Nearly Complete";
        return "Complete";
    }

    /**
     * Get quality status text
     */
    public String getQualityStatusText() {
        if (qualityScore == null) return "Unknown";
        
        if (qualityScore >= 90) return "Excellent";
        if (qualityScore >= 80) return "Good";
        if (qualityScore >= 70) return "Acceptable";
        if (qualityScore >= 60) return "Needs Improvement";
        return "Poor";
    }

    /**
     * Get time until deadline text
     */
    public String getTimeUntilDeadlineText() {
        long days = getDaysUntilDeadline();
        
        if (days < 0) return "Overdue";
        if (days == 0) return "Due Today";
        if (days == 1) return "Due Tomorrow";
        if (days <= 7) return days + " days";
        if (days <= 30) return (days / 7) + " weeks";
        return (days / 30) + " months";
    }

    /**
     * Get next action required text
     */
    public String getNextActionText() {
        if (status == null) return "Unknown";
        
        return switch (status) {
            case DRAFT -> "Start report development";
            case IN_PROGRESS -> "Continue development";
            case PENDING_REVIEW -> "Await compliance review";
            case UNDER_REVIEW -> "Under review";
            case REQUIRES_REVISION -> "Revise report";
            case PENDING_APPROVAL -> "Await approval";
            case APPROVED -> "Prepare for submission";
            case PREPARING_SUBMISSION -> "Complete submission";
            case SUBMITTED -> "Await acknowledgment";
            case FILED -> "Complete";
            case REJECTED -> "Address rejection issues";
            case CANCELLED -> "Cancelled";
            case OVERDUE -> "Immediate action required";
            case ON_HOLD -> "Resolve hold issues";
            case INFO_REQUESTED -> "Provide additional information";
            default -> "Review status";
        };
    }

    /**
     * Check if report has validation issues
     */
    public boolean hasValidationIssues() {
        return (validationErrorCount != null && validationErrorCount > 0) ||
               (validationWarningCount != null && validationWarningCount > 0);
    }

    /**
     * Get validation issues summary
     */
    public String getValidationIssuesSummary() {
        if (!hasValidationIssues()) return "No issues";
        
        StringBuilder summary = new StringBuilder();
        
        if (validationErrorCount != null && validationErrorCount > 0) {
            summary.append(validationErrorCount).append(" error");
            if (validationErrorCount > 1) summary.append("s");
        }
        
        if (validationWarningCount != null && validationWarningCount > 0) {
            if (summary.length() > 0) summary.append(", ");
            summary.append(validationWarningCount).append(" warning");
            if (validationWarningCount > 1) summary.append("s");
        }
        
        return summary.toString();
    }

    /**
     * Get financial summary text
     */
    public String getFinancialSummaryText() {
        if (financialSummary == null) return "No financial data";
        
        StringBuilder summary = new StringBuilder();
        
        if (financialSummary.getTotalAmount() != null) {
            summary.append("Total: ").append(financialSummary.getTotalAmount());
            if (financialSummary.getBaseCurrency() != null) {
                summary.append(" ").append(financialSummary.getBaseCurrency());
            }
        }
        
        if (financialSummary.getTransactionCount() != null && financialSummary.getTransactionCount() > 0) {
            if (summary.length() > 0) summary.append(", ");
            summary.append(financialSummary.getTransactionCount()).append(" transaction");
            if (financialSummary.getTransactionCount() > 1) summary.append("s");
        }
        
        return summary.length() > 0 ? summary.toString() : "No financial data";
    }

    /**
     * Create a basic summary from report ID and type
     */
    public static ComplianceReportSummary createBasic(String reportId, ComplianceReportType reportType, 
                                                     ComplianceReportStatus status, String title) {
        return ComplianceReportSummary.builder()
            .reportId(reportId)
            .reportType(reportType)
            .status(status)
            .title(title)
            .priority(reportType.getDefaultPriority())
            .createdAt(LocalDateTime.now())
            .completionPercentage(0)
            .build();
    }
}