package com.waqiti.common.events;

/**
 * Types of saga events
 */
public enum SagaEventType {
    // Saga lifecycle events
    SAGA_STARTED,
    SAGA_COMPLETED,
    SAGA_FAILED,
    SAGA_COMPENSATING,
    SAGA_COMPENSATED,
    SAGA_TIMEOUT,
    SAGA_CANCELLED,
    
    // Step execution events
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    STEP_RETRYING,
    STEP_COMPENSATING,
    STEP_COMPENSATED,
    STEP_SKIPPED,
    STEP_TIMEOUT,
    SAGA_STEP_UPDATED,
    SAGA_STEP_STATE_UPDATED,
    
    // Transaction events
    TRANSACTION_INITIATED,
    TRANSACTION_VALIDATED,
    TRANSACTION_AUTHORIZED,
    TRANSACTION_EXECUTED,
    TRANSACTION_CONFIRMED,
    TRANSACTION_REVERSED,
    
    // Payment events
    PAYMENT_INITIATED,
    PAYMENT_PROCESSING,
    PAYMENT_CAPTURED,
    PAYMENT_SETTLED,
    PAYMENT_REFUNDED,
    PAYMENT_DISPUTED,
    
    // Wallet events
    WALLET_DEBITED,
    WALLET_CREDITED,
    WALLET_LOCKED,
    WALLET_UNLOCKED,
    BALANCE_RESERVED,
    BALANCE_RELEASED,
    
    // Notification events
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED,
    NOTIFICATION_RETRYING,
    
    // Compliance events
    COMPLIANCE_CHECK_INITIATED,
    COMPLIANCE_CHECK_PASSED,
    COMPLIANCE_CHECK_FAILED,
    COMPLIANCE_REVIEW_REQUIRED,
    
    // Error events
    ERROR_OCCURRED,
    ERROR_HANDLED,
    ERROR_ESCALATED,
    
    // Monitoring events
    PERFORMANCE_DEGRADATION,
    THRESHOLD_EXCEEDED,
    CIRCUIT_BREAKER_OPENED,
    CIRCUIT_BREAKER_CLOSED
}