package com.waqiti.common.audit;

/**
 * Enumeration of audit event types for comprehensive audit logging
 */
public enum AuditEventType {
    // Authentication & Authorization
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    SESSION_TIMEOUT,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    MFA_SUCCESS,
    MFA_FAILURE,
    PERMISSION_GRANTED,
    PERMISSION_DENIED,
    
    // User Management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_LOCKED,
    USER_UNLOCKED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    
    // Financial Transactions
    TRANSACTION_INITIATED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    TRANSACTION_REVERSED,
    PAYMENT_SENT,
    PAYMENT_RECEIVED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_METHOD_CHANGED,
    PAYMENT_RETRY_SCHEDULED,
    PAYMENT_RETRY_CANCELLED,
    TRANSFER_INITIATED,
    TRANSFER_COMPLETED,
    WITHDRAWAL_INITIATED,
    WITHDRAWAL_COMPLETED,
    DEPOSIT_INITIATED,
    DEPOSIT_COMPLETED,
    
    // Account Operations
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_CLOSED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    WALLET_CREATED,
    WALLET_UPDATED,
    WALLET_DELETED,
    
    // Data Access
    DATA_READ,
    DATA_WRITE,
    DATA_DELETE,
    DATA_EXPORT,
    DATA_IMPORT,
    DATA_VIEW,
    DATA_ACCESS,
    REPORT_GENERATED,
    REPORT_EXPORTED,
    
    // Security Events
    SECURITY_ALERT,
    FRAUD_DETECTED,
    FRAUD_CONFIRMED,
    FRAUD_REJECTED,
    FRAUD_CHECK_COMPLETED,
    SUSPICIOUS_ACTIVITY,
    BLACKLIST_ADDED,
    BLACKLIST_REMOVED,
    IP_BLOCKED,
    IP_UNBLOCKED,
    
    // Compliance & KYC
    KYC_INITIATED,
    KYC_COMPLETED,
    KYC_FAILED,
    KYC_UPDATED,
    COMPLIANCE_CHECK,
    COMPLIANCE_PASSED,
    COMPLIANCE_FAILED,
    AML_CHECK,
    AML_ALERT,

    // Reconciliation Events
    RECONCILIATION_STARTED,
    RECONCILIATION_COMPLETED,
    RECONCILIATION_FAILED,
    DUPLICATE_RECONCILIATION_DETECTED,
    DISCREPANCY_DETECTED,
    DISCREPANCY_RESOLVED,
    AUTO_CORRECTION_APPLIED,
    ACCOUNTING_EVENT_PROCESSED,
    ACCOUNTING_EVENT_FAILED,
    
    // System Events
    SYSTEM_START,
    SYSTEM_STOP,
    SYSTEM_EVENT,
    CONFIGURATION_CHANGE,
    SERVICE_HEALTH_CHECK,
    BACKUP_CREATED,
    BACKUP_RESTORED,
    CIRCUIT_BREAKER_MANUAL_INTERVENTION,
    RESILIENCE_OPERATION,
    SETTLEMENT_PROCESSED,
    CHARGEBACK_RECEIVED,
    
    // API Operations
    API_REQUEST,
    API_RESPONSE,
    API_ERROR,
    WEBHOOK_SENT,
    WEBHOOK_RECEIVED,
    WEBHOOK_FAILED,
    
    // Administrative
    ADMIN_ACTION,
    BATCH_PROCESS_START,
    BATCH_PROCESS_COMPLETE,
    BATCH_PROCESS_FAILED,
    MAINTENANCE_MODE_ON,
    MAINTENANCE_MODE_OFF,
    HIGH_RISK_OPERATION,
    
    // Integration Events
    EXTERNAL_API_CALL,
    EXTERNAL_API_SUCCESS,
    EXTERNAL_API_FAILURE,
    THIRD_PARTY_INTEGRATION,
    
    // Error & Exception
    ERROR_OCCURRED,
    EXCEPTION_THROWN,
    CRITICAL_ERROR,
    
    // System Lifecycle Events
    SYSTEM_STARTUP,
    SYSTEM_SHUTDOWN,
    BACKGROUND_PROCESS,

    // Privilege & Access Control
    PRIVILEGE_ESCALATION,
    SECURITY_VIOLATION,

    // Data Operations
    SYSTEM_CONFIGURATION_CHANGE,

    // Financial & Transaction Events
    FINANCIAL_TRANSACTION,
    PAYMENT_PROCESSING,

    // Account & Customer Events
    ACCOUNT_MANAGEMENT,
    ACCOUNT_ACCESS,
    CUSTOMER_DATA_ACCESS,
    PERSONAL_DATA_PROCESSING,
    PRIVACY_OPERATION,

    // Security & Incident Events
    AUTHENTICATION,
    AUTHORIZATION,
    SECURITY_BREACH,
    DATA_BREACH,
    SYSTEM_COMPROMISE,

    // User Management Events
    USER_MANAGEMENT,

    // Audit System Events
    AUDIT_FAILURE,

    // Custom Events
    CUSTOM_EVENT
}