package com.waqiti.billpayment.entity;

/**
 * Categories for different types of bills
 */
public enum BillCategory {
    UTILITIES_ELECTRICITY,
    UTILITIES_WATER,
    UTILITIES_GAS,
    UTILITIES_TRASH,
    TELECOM_INTERNET,
    TELECOM_MOBILE,
    TELECOM_LANDLINE,
    TELECOM_CABLE_TV,
    INSURANCE_HEALTH,
    INSURANCE_AUTO,
    INSURANCE_HOME,
    INSURANCE_LIFE,
    CREDIT_CARD,
    LOAN_MORTGAGE,
    LOAN_AUTO,
    LOAN_PERSONAL,
    LOAN_STUDENT,
    SUBSCRIPTION_STREAMING,
    SUBSCRIPTION_SOFTWARE,
    SUBSCRIPTION_MEMBERSHIP,
    GOVERNMENT_TAX,
    GOVERNMENT_FINE,
    GOVERNMENT_FEE,
    EDUCATION_TUITION,
    EDUCATION_BOOKS,
    HEALTHCARE_MEDICAL,
    HEALTHCARE_DENTAL,
    HEALTHCARE_PHARMACY,
    RENT,
    HOA_FEES,
    CHILDCARE,
    OTHER
}
