package com.waqiti.common.security;

/**
 * Enumeration of security event types for monitoring and alerting
 */
public enum SecurityEventType {
    
    // Authentication Events
    LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_BLOCKED,
    LOGOUT,
    SESSION_EXPIRED,
    SESSION_HIJACKED,
    MULTI_FACTOR_AUTH_SUCCESS,
    MULTI_FACTOR_AUTH_FAILURE,
    PASSWORD_CHANGED,
    PASSWORD_RESET,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    
    // Authorization Events
    PERMISSION_DENIED,
    ACCESS_GRANTED,
    ACCESS_DENIED,
    PRIVILEGE_ESCALATION,
    ROLE_CHANGED,
    PERMISSION_CHANGED,
    UNAUTHORIZED_API_ACCESS,
    
    // Data Access Events
    DATA_ACCESS,
    SENSITIVE_DATA_ACCESS,
    DATA_EXPORT,
    DATA_MODIFICATION,
    DATA_DELETION,
    PII_ACCESS,
    FINANCIAL_DATA_ACCESS,
    
    // Security Violations
    BRUTE_FORCE_ATTACK,
    SQL_INJECTION_ATTEMPT,
    XSS_ATTEMPT,
    CSRF_ATTEMPT,
    RATE_LIMIT_EXCEEDED,
    SUSPICIOUS_ACTIVITY,
    MALICIOUS_REQUEST,
    
    // System Security Events
    SECURITY_POLICY_VIOLATION,
    CONFIGURATION_CHANGED,
    SECURITY_UPDATE_APPLIED,
    VULNERABILITY_DETECTED,
    ENCRYPTION_FAILURE,
    KEY_ROTATION,
    CERTIFICATE_EXPIRATION,
    
    // Network Security Events
    SUSPICIOUS_IP_ACCESS,
    GEOLOCATION_ANOMALY,
    VPN_DETECTED,
    TOR_DETECTED,
    PROXY_DETECTED,
    UNUSUAL_USER_AGENT,
    
    // Compliance Events
    GDPR_REQUEST,
    DATA_RETENTION_POLICY_APPLIED,
    AUDIT_LOG_ACCESS,
    COMPLIANCE_CHECK_FAILED,
    REGULATORY_ALERT,
    
    // Fraud Detection
    FRAUD_DETECTED,
    IDENTITY_VERIFICATION_FAILED,
    DEVICE_FINGERPRINT_MISMATCH,
    BEHAVIORAL_ANOMALY,
    TRANSACTION_ANOMALY,
    
    // Administrative Events
    ADMIN_LOGIN,
    ADMIN_ACTION,
    SYSTEM_CONFIG_CHANGE,
    USER_CREATED,
    USER_DELETED,
    BACKUP_COMPLETED,
    BACKUP_FAILED,
    
    // Security Alerts
    SECURITY_BREACH,
    DATA_LEAK,
    INSIDER_THREAT,
    EXTERNAL_THREAT,
    MALWARE_DETECTED,
    PHISHING_ATTEMPT,
    
    // Recovery Events
    ACCOUNT_RECOVERY,
    PASSWORD_RECOVERY,
    DEVICE_RESET,
    SESSION_RESTORED,
    
    // Monitoring Events
    LOG_TAMPERING,
    MONITORING_FAILURE,
    ALERT_TRIGGERED,
    INCIDENT_CREATED,
    INCIDENT_RESOLVED
}