package com.waqiti.virtualcard.domain;

/**
 * Transaction Type Enumeration
 */
public enum TransactionType {
    PURCHASE,
    REFUND,
    AUTHORIZATION,
    CAPTURE,
    VOID,
    REVERSAL,
    CHARGEBACK,
    CHARGEBACK_REVERSAL,
    ATM_WITHDRAWAL,
    ATM_BALANCE_INQUIRY,
    CASH_ADVANCE,
    BALANCE_TRANSFER,
    PAYMENT,
    ADJUSTMENT,
    FEE,
    INTEREST,
    CREDIT,
    DEBIT,
    PREAUTHORIZATION,
    PARTIAL_REFUND,
    FULL_REFUND,
    RECURRING_PAYMENT,
    SUBSCRIPTION,
    INSTALLMENT,
    QUASI_CASH,
    PIN_VERIFICATION,
    LOYALTY_REDEMPTION,
    CASHBACK,
    TIP_ADJUSTMENT,
    INCREMENTAL_AUTHORIZATION,
    PARTIAL_REVERSAL
}