package com.waqiti.account.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Result DTO for releasing reserved funds
 *
 * Reserved funds (holds) are temporary locks on account balance that prevent
 * those funds from being used for other transactions. Common scenarios:
 *
 * - Payment authorization (hold until capture/settlement)
 * - Security deposits (hold during rental/service period)
 * - Pending transaction holds (hold until confirmation)
 * - Dispute holds (hold during investigation)
 * - Compliance holds (hold pending verification)
 *
 * Release Operations:
 * - COMPLETE_RELEASE: Full hold amount returned to available balance
 * - PARTIAL_RELEASE: Part of hold released, remainder stays reserved
 * - CAPTURE: Hold converted to actual debit (not a release, but related)
 * - EXPIRE: Hold auto-released due to timeout
 * - CANCEL: Hold manually canceled (same as release)
 *
 * This DTO captures the outcome of a release operation including:
 * - Success/failure status
 * - Amount actually released
 * - Updated account balances
 * - Transaction references
 * - Audit trail information
 *
 * @author Production Readiness Team
 * @since 1.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReleaseReservedFundsResult {

    /**
     * Unique identifier for this release operation
     * Generated by the system
     */
    private UUID releaseId;

    /**
     * ID of the original hold/reservation
     */
    private UUID holdId;

    /**
     * Account ID where funds were reserved
     */
    private UUID accountId;

    /**
     * Success flag
     * True: Release completed successfully
     * False: Release failed (hold not found, already released, etc.)
     */
    private Boolean success;

    /**
     * Result status code
     * Values: SUCCESS, PARTIAL_SUCCESS, FAILED, ALREADY_RELEASED,
     *         HOLD_NOT_FOUND, ACCOUNT_CLOSED, VALIDATION_ERROR
     */
    private String status;

    /**
     * Human-readable message explaining the result
     * Examples: "Hold released successfully", "Hold already expired"
     */
    private String message;

    /**
     * Original hold amount (total amount that was reserved)
     */
    private BigDecimal originalHoldAmount;

    /**
     * Amount actually released in this operation
     * May be less than originalHoldAmount for partial releases
     */
    private BigDecimal releasedAmount;

    /**
     * Remaining hold amount after this release
     * 0 for complete release, >0 for partial release
     */
    private BigDecimal remainingHoldAmount;

    /**
     * Account balance before the release
     */
    private BigDecimal balanceBeforeRelease;

    /**
     * Account balance after the release
     * Should equal balanceBeforeRelease (total balance unchanged)
     */
    private BigDecimal balanceAfterRelease;

    /**
     * Available balance before the release
     */
    private BigDecimal availableBalanceBeforeRelease;

    /**
     * Available balance after the release
     * Should increase by releasedAmount
     */
    private BigDecimal availableBalanceAfterRelease;

    /**
     * Currency of the amounts (ISO 4217)
     */
    private String currency;

    /**
     * Timestamp when the release was processed
     */
    private LocalDateTime releaseTimestamp;

    /**
     * Original hold creation timestamp
     */
    private LocalDateTime holdCreatedAt;

    /**
     * Hold expiration timestamp (if applicable)
     */
    private LocalDateTime holdExpiresAt;

    /**
     * Release type
     * Values: MANUAL, AUTOMATIC_EXPIRY, CAPTURE, CANCEL, TIMEOUT
     */
    private String releaseType;

    /**
     * Reason for the release
     * Examples: "Payment canceled", "Authorization expired", "Dispute resolved"
     */
    private String releaseReason;

    /**
     * User ID who initiated the release (if manual)
     */
    private UUID initiatedBy;

    /**
     * Transaction reference for this release operation
     * Links to transaction/audit logs
     */
    private String transactionReference;

    /**
     * Original reference that created the hold
     * For traceability back to source transaction
     */
    private String originalHoldReference;

    /**
     * External system ID (e.g., payment processor reference)
     */
    private String externalSystemId;

    /**
     * Hold description/purpose
     */
    private String holdDescription;

    /**
     * Processing time in milliseconds
     * For performance monitoring
     */
    private Long processingTimeMs;

    /**
     * Flag indicating if this was a partial release
     */
    private Boolean partialRelease;

    /**
     * Flag indicating if hold expired automatically
     */
    private Boolean expiredHold;

    /**
     * Validation errors (if any)
     * Populated when success = false
     */
    private String errorCode;

    /**
     * Detailed error message (if any)
     */
    private String errorDetails;

    /**
     * Additional metadata about the release
     * JSON format for extensibility
     */
    private String metadata;

    /**
     * Checks if the release was completely successful
     */
    public boolean isCompleteSuccess() {
        return Boolean.TRUE.equals(success) &&
               "SUCCESS".equals(status) &&
               remainingHoldAmount != null &&
               remainingHoldAmount.compareTo(BigDecimal.ZERO) == 0;
    }

    /**
     * Checks if this was a partial release
     */
    public boolean isPartialRelease() {
        return Boolean.TRUE.equals(partialRelease) ||
               (remainingHoldAmount != null && remainingHoldAmount.compareTo(BigDecimal.ZERO) > 0);
    }

    /**
     * Checks if the hold expired automatically
     */
    public boolean wasExpired() {
        return Boolean.TRUE.equals(expiredHold) || "AUTOMATIC_EXPIRY".equals(releaseType);
    }

    /**
     * Checks if this was a manual release
     */
    public boolean wasManualRelease() {
        return "MANUAL".equals(releaseType) && initiatedBy != null;
    }

    /**
     * Validates that available balance increased correctly
     * Available balance should increase by exactly the released amount
     */
    public boolean isBalanceConsistent() {
        if (availableBalanceBeforeRelease == null ||
            availableBalanceAfterRelease == null ||
            releasedAmount == null) {
            return false;
        }

        BigDecimal expectedAvailableBalance =
            availableBalanceBeforeRelease.add(releasedAmount);

        return expectedAvailableBalance.compareTo(availableBalanceAfterRelease) == 0;
    }

    /**
     * Calculates the percentage of hold released
     * Returns value between 0 and 100
     */
    public BigDecimal getPercentageReleased() {
        if (originalHoldAmount == null ||
            originalHoldAmount.compareTo(BigDecimal.ZERO) == 0 ||
            releasedAmount == null) {
            return BigDecimal.ZERO;
        }

        return releasedAmount
            .multiply(new BigDecimal("100"))
            .divide(originalHoldAmount, 2, java.math.RoundingMode.HALF_UP);
    }

    /**
     * Checks if the hold has expired (based on expiration date)
     */
    public boolean isHoldExpired() {
        return holdExpiresAt != null && LocalDateTime.now().isAfter(holdExpiresAt);
    }

    /**
     * Gets hold duration in hours
     */
    public Long getHoldDurationHours() {
        if (holdCreatedAt == null || releaseTimestamp == null) {
            return null;
        }

        return java.time.Duration.between(holdCreatedAt, releaseTimestamp).toHours();
    }

    /**
     * Checks if this is an error result
     */
    public boolean hasError() {
        return Boolean.FALSE.equals(success) || errorCode != null;
    }

    /**
     * Gets a summary string for logging
     */
    public String getSummary() {
        if (Boolean.TRUE.equals(success)) {
            return String.format(
                "Released %s %s (%.1f%%) from hold %s on account %s",
                releasedAmount, currency,
                getPercentageReleased().doubleValue(),
                holdId, accountId
            );
        } else {
            return String.format(
                "Failed to release hold %s on account %s: %s",
                holdId, accountId, message
            );
        }
    }

    /**
     * Creates a success result
     */
    public static ReleaseReservedFundsResult success(
        UUID releaseId,
        UUID holdId,
        UUID accountId,
        BigDecimal releasedAmount,
        BigDecimal availableBalanceBefore,
        BigDecimal availableBalanceAfter,
        String currency
    ) {
        return ReleaseReservedFundsResult.builder()
            .releaseId(releaseId)
            .holdId(holdId)
            .accountId(accountId)
            .success(true)
            .status("SUCCESS")
            .message("Hold released successfully")
            .releasedAmount(releasedAmount)
            .remainingHoldAmount(BigDecimal.ZERO)
            .availableBalanceBeforeRelease(availableBalanceBefore)
            .availableBalanceAfterRelease(availableBalanceAfter)
            .currency(currency)
            .releaseTimestamp(LocalDateTime.now())
            .partialRelease(false)
            .build();
    }

    /**
     * Creates a failure result
     */
    public static ReleaseReservedFundsResult failure(
        UUID holdId,
        UUID accountId,
        String status,
        String message,
        String errorCode
    ) {
        return ReleaseReservedFundsResult.builder()
            .holdId(holdId)
            .accountId(accountId)
            .success(false)
            .status(status)
            .message(message)
            .errorCode(errorCode)
            .releaseTimestamp(LocalDateTime.now())
            .build();
    }

    /**
     * Creates a partial release result
     */
    public static ReleaseReservedFundsResult partialRelease(
        UUID releaseId,
        UUID holdId,
        UUID accountId,
        BigDecimal originalAmount,
        BigDecimal releasedAmount,
        BigDecimal remainingAmount,
        String currency
    ) {
        return ReleaseReservedFundsResult.builder()
            .releaseId(releaseId)
            .holdId(holdId)
            .accountId(accountId)
            .success(true)
            .status("PARTIAL_SUCCESS")
            .message("Partial hold release completed")
            .originalHoldAmount(originalAmount)
            .releasedAmount(releasedAmount)
            .remainingHoldAmount(remainingAmount)
            .currency(currency)
            .releaseTimestamp(LocalDateTime.now())
            .partialRelease(true)
            .build();
    }
}
