package com.waqiti.ledger.dto;

public enum DiscrepancyType {
    MISSING_IN_BANK,
    MISSING_IN_BOOKS,
    AMOUNT_MISMATCH,
    DATE_MISMATCH,
    DUPLICATE_IN_BANK,
    DUPLICATE_IN_BOOKS,
    UNMATCHED_DEPOSIT,
    UNMATCHED_WITHDRAWAL,
    STALE_CHECK,
    NSF_CHECK,
    BANK_FEE,
    INTEREST_EARNED,
    CURRENCY_VARIANCE,
    ROUNDING_DIFFERENCE,
    OTHER
}