package com.waqiti.ledger.dto;

public enum ResolutionMethod {
    WRITE_OFF,
    ADJUSTMENT_ENTRY,
    BANK_ERROR,
    TIMING_DIFFERENCE,
    DUPLICATE_ENTRY,
    MISSING_ENTRY,
    INCORRECT_AMOUNT,
    CURRENCY_DIFFERENCE,
    REVERSAL,
    MANUAL_MATCH,
    AUTOMATED_MATCH,
    SPLIT_TRANSACTION,
    COMBINE_TRANSACTIONS,
    RECLASSIFICATION,
    OTHER
}