package com.waqiti.recurringpayment.config;

import com.waqiti.common.security.keycloak.BaseKeycloakSecurityConfig;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.web.SecurityFilterChain;
import lombok.extern.slf4j.Slf4j;

/**
 * Keycloak security configuration for RecurringPaymentService
 * Auto-generated by migration script
 */
@Slf4j
@Configuration
@ConditionalOnProperty(name = "keycloak.enabled", havingValue = "true")
@Order(1)
public class RecurringPaymentServiceKeycloakConfig extends BaseKeycloakSecurityConfig {

    @Bean
    @Primary
    public SecurityFilterChain recurringpaymentserviceKeycloakFilterChain(HttpSecurity http) throws Exception {
        return createKeycloakSecurityFilterChain(http, "recurring-payment-service", httpSecurity -> {
            httpSecurity.authorizeHttpRequests(authz -> authz
                // Public endpoints
                .requestMatchers("/actuator/health", "/actuator/info").permitAll()
                .requestMatchers("/swagger-ui/**", "/v3/api-docs/**").permitAll()
                
                // Recurring payment endpoints - requires authenticated users
                .requestMatchers("/api/v1/recurring-payments/**").authenticated()
                .requestMatchers("/api/v1/scheduled-payments/**").authenticated()
                .requestMatchers("/api/v1/subscription-payments/**").authenticated()
                .requestMatchers("/api/v1/payment-templates/**").authenticated()
                
                // Admin endpoints
                .requestMatchers("/admin/**").hasRole("ADMIN")
                
                // Internal service-to-service endpoints
                .requestMatchers("/internal/**").hasRole("SERVICE")
                
                // All other endpoints require authentication
                .anyRequest().authenticated()
            );
        });
    }
}
